import java.util.*;
// 1. Our Custom Checked Exception
class InvalidAgeException extends Exception { // [cite: 156]
    public InvalidAgeException(String message) {
        super(message);
    }
}

public class exceptionHandling {

    // 2. The THROWS keyword declares a warning in the method signature.
    // It tells the main method: "Hey, if you call me, be prepared to handle an
    // InvalidAgeException!"
    public static void validateAge(int age) throws InvalidAgeException {
        if (age < 18) {
            // 3. The THROW keyword actively triggers the exception right here
            throw new InvalidAgeException("Age must be 18 or above to register."); // [cite: 158]
        }
        System.out.println("Registration successful! Age is valid.");
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int age = sc.nextInt();
        try {
            // Calling the method that has a 'throws' declaration
            validateAge(age);
        } catch (InvalidAgeException e) { // [cite: 160]
            // Handling the exception that was generated by the 'throw' keyword
            System.out.println("Registration Failed: " + e.getMessage()); // [cite: 160]
        }
    }
}